import { Inter } from "next/font/google";
import "./globals.css";
import { GlobalState } from "@/context";
import { Toaster } from 'react-hot-toast'
import AuthProvider from "@/components/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Welcome to our Agency",
  description: "Generated by create agency app",
};
  
export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={inter.className} suppressHydrationWarning={true}>
          <GlobalState>
            <AuthProvider>
              {children}
            </AuthProvider>
          </GlobalState>
        <Toaster position="top-center" reverseOrder={false} />
      </body>
    </html>
  );
}
